
# have to call those in this file 
# make this the main file to control flow and configs


### ssh

SSH_ENV="$HOME/.ssh/environment"

function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi


### run bash aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


# generated by Git for Windows
#test -f ~/.profile && . ~/.profile
#test -f ~/.bashrc && . ~/.bashrc

# run .bashrc
if [ -f ~/.bashrc ]; then 
    . ~/.bashrc
fi

# set up local conda (no activating any envs)
. /c/Users/samuel.tan/Miniconda3/etc/profile.d/conda.sh

echo ".bash_profile run"
